name: Lab1 

on: 
  push:
    branches: main
    

jobs: 
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.creation.outputs.test}} 
    steps: 
      - name: Variable Creation
        id: creation
        run: echo "test=hello" >> "$GITHUB_OUTPUT"

  deploy: 
    runs-on: ubuntu-latest
    needs: build
    environment: Secret_test
    steps: 
      - run: echo "My variable ${{needs.build.outputs.output1}}"



    
