name: Lab1

on: 
  push:
    branches:
      main

jobs: 
  build:
    runs-on: ubuntu-latest
    env: 
      VERSION: ${{ github.sha }}
    steps: 
      - name: Test
        uses: actions/checkout@v4      
      - run: VERSION >> $GITHUB_OUTPUT
  deploy: 
    runs-on: ubuntu-latest
    env: 
      PRODUCTION: ${{ secrets.Secret_test}}
    needs: build
    steps:
      - name: Output
        run: echo "This is the hash variable {{ needs.build.outputs.VERSION }}"
    
