name: Consumption-lab6

on:
    push

jobs: 
    job1: 
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            - name: composite consume
              id: setup
              uses: ./.github/actions/lab6              
              with:
                python-version: '3.12'
            - name: print version 
              run: echo "The python version on this lab is " "${{ steps.setup.outputs.cache-hit }}"
              