name: Consumption-lab6

on:
    push

jobs: 
    job1: 
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            - name: Setup python environment
              id: setup
              uses: ./.github/actions/setup-python-env              
              with:
                python-version: '3.12'
            - name: Print cache status 
              run: echo "The python version on this lab is " "${{ steps.setup.outputs.cache-hit }}"
              