name: reusable

on: 
    workflow_call:
        inputs:
            environment: 
                description: "Target secret"
                required: true
                type: string
        secrets: 
            API_SECRET: 
                required: true

jobs: 
    job1:
        environment: API_TEST
        env: 
                API_KEY: ${{secrets.API_SECRET}}
        runs-on: ubuntu-latest
        steps:
            - name: Print Token
              uses: actions/checkout@v4              
            - name: Print Token
              run: echo "The API_TOKEN issssss " "$API_KEY" "And the input received is" "{{ inputs.environment }}"

